version: 1
strains:
  - code:
      protocol: https
      host: github.com
      hostname: github.com
      owner: adobe
      repo: developer.adobe.com
      ref: master
    content:
      protocol: https
      host: github.com
      hostname: github.com
      owner: adobe
      repo: developer.adobe.com
      ref: master
    static:
      protocol: https
      host: github.com
      hostname: github.com
      owner: adobe
      repo: developer.adobe.com
      ref: master
      path: /htdocs
    directoryIndex: index.html
    package: developer-adobe-com/a4ffc65af292c60d34ffe01a052b14228ccf8520
    name: default
  - code:
      protocol: https
      host: github.com
      hostname: github.com
      owner: adobe
      repo: developer.adobe.com
      ref: master
    content:
      protocol: https
      host: github.com
      hostname: github.com
      owner: Adobe-Marketing-Cloud
      repo: reactor-user-docs
      ref: master
    static:
      protocol: https
      host: github.com
      hostname: github.com
      owner: adobe
      repo: developer.adobe.com
      ref: master
      path: /htdocs
    directoryIndex: README.html
    package: developer-adobe-com/a4ffc65af292c60d34ffe01a052b14228ccf8520
    name: launch-docs-helixdemo
    urls:
      - https://adobedevsite.helix-demo.xyz/launch/docs
    url: https://adobedevsite.helix-demo.xyz/launch/docs
  - code:
      protocol: https
      host: github.com
      hostname: github.com
      owner: adobe
      repo: developer.adobe.com
      ref: master
    content:
      protocol: https
      host: github.com
      hostname: github.com
      owner: AdobeXD
      repo: plugin-docs
      ref: master
    static:
      protocol: https
      host: github.com
      hostname: github.com
      owner: adobe
      repo: developer.adobe.com
      ref: master
      path: /htdocs
    directoryIndex: README.html
    package: developer-adobe-com/a4ffc65af292c60d34ffe01a052b14228ccf8520
    name: xd-docs-helixdemo
    urls:
      - https://adobedevsite.helix-demo.xyz/xd/docs
    url: https://adobedevsite.helix-demo.xyz/xd/docs
  - code:
      protocol: https
      host: github.com
      hostname: github.com
      owner: adobe
      repo: developer.adobe.com
      ref: master
    content:
      protocol: https
      host: github.com
      hostname: github.com
      owner: AdobeDocs
      repo: starter-docs
      ref: master
    static:
      protocol: https
      host: github.com
      hostname: github.com
      owner: adobe
      repo: developer.adobe.com
      ref: master
      path: /htdocs
    directoryIndex: Overview.html
    package: developer-adobe-com/a4ffc65af292c60d34ffe01a052b14228ccf8520
    name: starter-docs-helixdemo
    urls:
      - https://adobedevsite.helix-demo.xyz/starter/docs
    url: https://adobedevsite.helix-demo.xyz/starter/docs
  - code:
      protocol: https
      host: github.com
      hostname: github.com
      owner: adobe
      repo: developer.adobe.com
      ref: master
    content:
      protocol: https
      host: github.com
      hostname: github.com
      owner: adobe
      repo: developer.adobe.com
      ref: master
    static:
      protocol: https
      host: github.com
      hostname: github.com
      owner: adobe
      repo: developer.adobe.com
      ref: master
      path: /htdocs
    directoryIndex: index.html
    package: developer-adobe-com/a4ffc65af292c60d34ffe01a052b14228ccf8520
    name: helix-demo
    urls:
      - https://adobedevsite.helix-demo.xyz/
    url: https://adobedevsite.helix-demo.xyz/
