# Copyright 2018 Adobe. All rights reserved.
# This file is licensed to you under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License. You may obtain a copy
# of the License at http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under
# the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
# OF ANY KIND, either express or implied. See the License for the specific language
# governing permissions and limitations under the License.

version: 1

definitions:
  defaults:
    # Run default content from github repo
    #- &defaultRepo https://github.com/adobe/developer.adobe.com.git#master
    # Run default content from this repo locally
    - &defaultRepo "http://localhost/local/default.git"
  strains:
    base:
      &basestrain
      code: *defaultRepo
      content: *defaultRepo
      static: *defaultRepo
      package: 16cd39e4810356ecc384bb5185f081e23cae229b
    proxy:
      &proxystrain
      origin:
        address: 34.227.208.69
        use_ssl: true
        ssl_cert_hostname: www.adobe.io

strains:
  default:
    <<: *basestrain
    package: 9e81a2d5d82f2a22bf218b446da32414f33c0d87

  launch-docs-prod:
    <<: *basestrain
    url: https://www.adobe.io/launch/docs
    content: https://github.com/Adobe-Marketing-Cloud/reactor-user-docs.git#master
    directoryIndex: README.html
    package: 237482f2d0adca81a463661842c85d5e89bb9228

  launch-docs-stage:
    <<: *basestrain
    url: https://stage.adobe.io/launch/docs
    content: https://github.com/Adobe-Marketing-Cloud/reactor-user-docs.git#master
    directoryIndex: README.html
    package: 237482f2d0adca81a463661842c85d5e89bb9228

  launch-docs-local:
    <<: *basestrain
    url: http://localhost:3000/launch/docs
    content: https://github.com/Adobe-Marketing-Cloud/reactor-user-docs.git#master
    directoryIndex: README.html
    package: 237482f2d0adca81a463661842c85d5e89bb9228

  helix-demo:
    url: https://adobedevsite.helix-demo.xyz/
    code: ssh://git@github.com/adobe/developer.adobe.com.git#master
    content: ssh://git@github.com/adobe/developer.adobe.com.git#master
    static: https://github.com/adobe/developer.adobe.com.git#master/htdocs
    package: 4e4f2a2b08ecc8b5509002511000b84000e00290

  launch-docs-helixdemo:
    <<: *basestrain
    url: https://adobedevsite.helix-demo.xyz/launch/docs
    content: https://github.com/Adobe-Marketing-Cloud/reactor-user-docs.git#master
    directoryIndex: README.html
    package: 237482f2d0adca81a463661842c85d5e89bb9228

  xd-docs-helixdemo:
    <<: *basestrain
    url: https://adobedevsite.helix-demo.xyz/xd/docs
    content: https://github.com/AdobeXD/plugin-docs.git#master
    directoryIndex: README.html
    package: e5e0925f5bdb13d50c55ce4ff50e97660a112a53

  xd-docs-prod:
    <<: *basestrain
    url: https://www.adobe.io/xd/docs
    content: https://github.com/AdobeXD/plugin-docs.git#master
    directoryIndex: README.html
    package: e5e0925f5bdb13d50c55ce4ff50e97660a112a53

  xd-docs-stage:
    <<: *basestrain
    url: https://stage.adobe.io/xd/docs
    content: https://github.com/AdobeXD/plugin-docs.git#master
    directoryIndex: README.html
    package: e5e0925f5bdb13d50c55ce4ff50e97660a112a53

  xd-docs-local:
    <<: *basestrain
    url: http://localhost:3000/xd/docs
    content: https://github.com/AdobeXD/plugin-docs.git#master
    directoryIndex: README.html
    package: e5e0925f5bdb13d50c55ce4ff50e97660a112a53

  xd-marketing-prod:
    <<: *basestrain
    url: https://www.adobe.io/xd
    content: https://github.com/AdobeXD/plugin-docs.git#master
    directoryIndex: README.html
    package: 9e81a2d5d82f2a22bf218b446da32414f33c0d87

  xd-marketing-stage:
    <<: *basestrain
    url: https://stage.adobe.io/xd
    content: https://github.com/AdobeXD/plugin-docs.git#author
    directoryIndex: README.html
    package: 9e81a2d5d82f2a22bf218b446da32414f33c0d87

  xd-marketing-local:
    <<: *basestrain
    url: https://localhost:3000/xd
    content: https://github.com/AdobeXD/plugin-docs.git#author
    directoryIndex: README.html
    package: 9e81a2d5d82f2a22bf218b446da32414f33c0d87

  starter-docs-prod:
    <<: *basestrain
    url: https://www.adobe.io/starter/docs
    content: https://github.com/AdobeDocs/starter-docs.git#master
    directoryIndex: Overview.html
    package: 8e2de5067caf322aeb8465060400209f77c2c538

  starter-docs-stage:
    <<: *basestrain
    url: https://stage.adobe.io/starter/docs
    content: https://github.com/AdobeDocs/starter-docs.git#author
    directoryIndex: Overview.html
    package: 8e2de5067caf322aeb8465060400209f77c2c538

  starter-docs-local:
    <<: *basestrain
    url: http://localhost:3000/starter/docs
    content: https://github.com/AdobeDocs/starter-docs.git#author
    directoryIndex: Overview.html
    package: 8e2de5067caf322aeb8465060400209f77c2c538
