version: 2.1
executors:
  helix:
    docker:
      - image: circleci/node:8-jessie-browsers
jobs:
  install:
    executor: helix
    steps:
        - checkout

        # Download and cache dependencies
        - restore_cache:
            keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-

        - run:
            name: Installing Dependencies
            command: npm install

        - save_cache:
            paths:
              - node_modules
            key: v1-dependencies-{{ checksum "package-lock.json" }}

  build:
    executor: helix
    steps:
        - checkout
        - restore_cache:
            keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-

        - run:
            name: Build helix
            command: npm run build

  test:
    executor: helix
    steps:
        - checkout
        - restore_cache:
            keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-

        # run tests!
        - run:
            name: prepare test git user
            command: git config --global user.email "you@example.com" && git config --global user.name "CircleCi Build"

        - run:
            name: Test
            command: npm test

workflows:
  version: 2.1
  continously_integrate:
    jobs:
      - install
      - build:
          requires:
            - install
      - test:
          requires:
            - build
